[paths]
raw_dir = "data/data_raw"
processed_dir = "data/data_processed"

[data]
raw_filename = "Loan_default.csv"   # adjust if your file name differs

[train]
test_size = 0.2
random_state = 42
stratify = true
